### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by boghilife** [Kenta30/characterkill#1]
Hi, when I run the "ck" command I got this error. Even sql tables are not deleted.
I'm using a fresh version of esx_legacy/oxmysql (installed today).
![db_error](https://github.com/Kenta30/characterkill/assets/69466315/93db1c12-298f-4bc5-997b-7582b8f97adc)

**Comment by KentaNo1** [comment]
Hi, i assume you don't have esx documents. Comment out those lines where there is no sql table and add your own tables.
